version: "2.2"

services:
  app:
    environment:
      TB_BASE_URL: "http://192.168.10.130:8080"
      TB_TOKEN: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzeXNhZG1pbkB0aGluZ3Nib2FyZC5vcmciLCJ1c2VySWQiOiIxZDYyNDY4MC1mMTIxLTExZjAtODA3Zi1mZmFkYTg1ZTBmZWYiLCJzY29wZXMiOlsiU1lTX0FETUlOIl0sInNlc3Npb25JZCI6IjY5NmVkYjYwLTQyMzUtNDIxOS1hMWExLTA4MTY0NDJkMDA0YSIsImV4cCI6MTc2OTUxMTE0MCwiaXNzIjoidGhpbmdzYm9hcmQuaW8iLCJpYXQiOjE3Njk1MDIxNDAsImVuYWJsZWQiOnRydWUsImlzUHVibGljIjpmYWxzZSwidGVuYW50SWQiOiIxMzgxNDAwMC0xZGQyLTExYjItODA4MC04MDgwODA4MDgwODAiLCJjdXN0b21lcklkIjoiMTM4MTQwMDAtMWRkMi0xMWIyLTgwODAtODA4MDgwODA4MDgwIn0.QfQt6_jEko137ZCrmbFqUcusXuUaxqeyQT4i162dL_owPFgD-4_hPdbOUSmpnZv7sPr02KkDRHmH7LYXxlOAIg"
      HTTP_ADDR: ":8081"
      INGEST_HMAC_SECRET: "dev-ingest-secret"
    ports:
      - "8081:8081"
